site_name: BitClouded Infrastructure Framework
pages:
  - Home: 'index.md'
  - Aspects:
    - 'Security': 'pillars/security.md'
    - 'Monitoring': 'pillars/monitoring.md'
    - 'Operations': 'pillars/operations.md'